ROWS = 20
COLUMNS = 30
TILE_SIZE =  32
SIDE_PANEL = 250
SCREEN_WIDTH = TILE_SIZE * COLUMNS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 650
TOTAL_LEVELS = 20
#turret constants
ANIMATION_FRAMES = 8
ANIMATION_DELAY = 15
MAX_LEVEL = 4
BUY_COST = 200
UPGRADE_COST = 100
DAMAGE = 10
#enemy constants
SPAWN_COOLDOWN = 400
KILL_REWARD = 20